### ISSUE TITLE
Terrascan: Not working in a Repository referencing other repository

### ISSUE THREAD

**Issue by PrateekKhatri** [accurics/terrascan#1030]
Hi Team,

I have one private repository that contains terraform modules (let's say repo1) and the other private repository which is referencing to terraform module repository (let's say repo2) .
While adding terrascan GitHub action to repo2 it is failing to run terrascan with the below error:

terrascan scan  -d . -i terraform --iac-version v14 -t aws
2021-09-22T12:40:32.157Z	error	downloader/getter.go:105	failed to download error: 'error downloading 
 /usr/bin/git exited with 128: Cloning into '/tmp/ryinov'...
fatal: could not read Username for 'https://github.com': No such device or address

**Comment by cesar-rodriguez** [comment]
Hi @PrateekKhatri,

I'm closing this issue as we're tracking it on the GitHub action repository here https://github.com/accurics/terrascan-action/issues/16. There's an open PR that we're finalizing to address this issue https://github.com/accurics/terrascan-action/pull/22
