### ISSUE TITLE
Is it possible to use terrascan in an offline environment

### ISSUE THREAD

**Issue by johnqa** [accurics/terrascan#1154]
* terrascan version: 1.13.1
* Operating System: RedHat

### Description

I am trying to run terrascan in an air gapped environment. 
I have downloaded terrascan policies folders and put them on a local server then I tried to run a scan using the docker image. 
I am getting an error that says it cannot connect to github (which is fair as I don;t have connectivity) but I would expect for the scan to use the policies from the directory Iam indicating in the command.

### What I Did

```
 sudo docker run --rm -it -v "/home/user/testing/terraform:/iac" -v /home/user/testing/terrascan/pkg/policies/opa/rego:/policies -w /iac accurics/terrascan scan -l "error" -p /policies -d /iac -v -i terraform

2022-02-16T10:24:27.422Z error cli/init.go:42 failed to initialize terrascan. error : could not connect to github.com
```

Is there a way to work around this issue?

**Comment by kanchwala-yusuf** [comment]
Hey @johnqa,

Thanks for using terrascan. 

So, `terrascan` checks for `$HOME/.terrascan` directory on the filesystem and if this directory does not exist, downloads the terrascan repository onto `$HOME/.terrascan`.

Can you try cloning terrascan locally and then mount it onto `$HOME/.terrascan` inside the terrascan container?

Do let me know if it works

**Comment by johnqa** [comment]
Hi,

Your advice worked. It took me a while to implement, but after I looked at the Dockerfile from the git repo I sorted it out.

The working call is:
```docker run --rm -v "/home/user/testing/terraform/:/iac" -v "/home/user/testing/terrascan/pkg/policies/opa/rego:/home/terrascan/.terrascan/pkg/policies/opa/rego" -w /iac accurics/terrascan scan -l "error" -p /home/terrascan/.terrascan/pkg/policies/opa/rego -d /iac```

Thanks

**Comment by flcdrg** [comment]
If you're using `github/super-linter` to run terrascan, I figured out that the volume mapping should look like ` -v /home/user/testing/terrascan/pkg/policies/opa/rego:/terrascan/.terrascan/pkg/policies/opa/rego`
