### ISSUE TITLE
Be able to generate xml/html reports

### ISSUE THREAD

**Issue by supergarotinho** [accurics/terrascan#119]
* terrascan version: n/a
* Python version: n/a
* Operating System: n/a

### Description

Be able to pass parameters like: [--xml-report dir] or [--html-report dir] and generate these reports

**Comment by supergarotinho** [comment]
One suggestions is using html-testRunner and xmlrunner

**Comment by ugocupcic** [comment]
Dirty hack for now, but I've implemented a fork that generates xml junit reports [in a fork](https://github.com/ugocupcic/terrascan). Not sure when I'll have time to cleanup the code and submit a merge request though.

**Comment by cesar-rodriguez** [comment]
@ugocupcic Would you mind opening a PR and allowing me permissions to modify your fork? I can help clean the code up before merging.

**Comment by nightwatchcyber** [comment]
@ugocupcic +1 for junit xml support

**Comment by cesar-rodriguez** [comment]
This was fixed with #291
