### ISSUE TITLE
Terrascan 1.13.2 version uses go 1.16.14 version which has High vulnerability. When can we expect the release with go version 1.17?

### ISSUE THREAD

**Issue by SayaliMane05** [accurics/terrascan#1190]

**Comment by cesar-rodriguez** [comment]
Hi @SayaliMane05, we're planning to release the new version with 1.17 by tomorrow.

**Comment by SayaliMane05** [comment]
Thank you @cesar-rodriguez

**Comment by Rchanger** [comment]
With the latest release, we are now using go 1.17. @SayaliMane05 Thanks for reporting the issue.

**Comment by SayaliMane05** [comment]
Hi, I see some vulnerabilities in latest terrascan version 1.16.0 :
1. Latest terrascan version contains Go version 1.19.1 which is vulnerable. This is fixed in go version 1.19.2, 1.18.7
2. Latest terrascan version contains go-getter version 1.5.11 which is vulnerable. This vulnerability is fixed in go-getter version 1.6.1 and 2.1.0
3. open-policy-agent/opa version 0.22.0 is vulnerable. This is fixed in version 0.42.0
When can we expect the release with these vulnerabilities fixed?
Thanks,
Sayali.
