### ISSUE TITLE
Terrascan -var-file=../another dir

### ISSUE THREAD

**Issue by MichaelSmyth0184** [accurics/terrascan#144]
* terrascan version: 0.11.13
* Python version: 3.6.5
* Operating System: Centos 7

### Description

Running terrascan on .tf files that reference modules which pull input values from a .tfvars file located in another directory.

### What I Did

```
terrascan --location . --tests all
All tests apparently passed, even though In the terrascan command I could not do a -var-file="../test,tfvars" for the input values.
```

Any help on this would be great.

**Comment by cesar-rodriguez** [comment]
Support for modules was added on #345
