### ISSUE TITLE
Terrascan print out rules in human friendly format?

### ISSUE THREAD

**Issue by munntjlx** [accurics/terrascan#168]
### Description

I would like to 'print out' the rules that things test for in a comprehensive format (csv, json, yaml) so I can put into CMDB and manage 'centrally' for my auditors etc. The function definitions in the test modules are somewhat hard to read. Some examples of desired types of output:
### types of output
CSV:
aws_ami_copy, 'Assert resources are encrypted', 'Property: encrypted', 'expected: kms_key_id"

Markdown:
# Rule Name Assert Resources are Encrypted

**Comment by cesar-rodriguez** [comment]
Hi @munntjlx with v1.0.0 we're including a ".json" rules file with each rego policy [here](https://github.com/accurics/terrascan/tree/master/pkg/policies/opa/rego). I think a good enhancement would be to have a command, like you suggest, to export the rule information that's configured in your local environment regardless of what's included in the repository by default.

**Comment by cesar-rodriguez** [comment]
This was resolved by #431
