### ISSUE TITLE
Support from modules

### ISSUE THREAD

**Issue by cesar-rodriguez** [accurics/terrascan#2]
Terrascan should detect any modules in the terraform templates and scan them.

**Comment by Clete2** [comment]
Is there any support in Terrascan for modules? Any workaround?

**Comment by sbalbach** [comment]
see pull request #150

**Comment by lachie-white** [comment]
Is this still an open issue, having issues attempting to scan modules, as it's all we really use

**Comment by kanchwala-yusuf** [comment]
Terrascan v1.0.0 supports terraform modules, currently only [Local Paths](https://www.terraform.io/docs/modules/sources.html#local-paths) source type is supported.

Terrascan supports terraform module traversal for IaC scanning with `terrascan scan` command only when `-d` flag is specified; `-d` takes path to a directory containing IaC files as an input.

Terrascan internally implements a `ModuleWalker` which recursively traverses through all the `Local Path` module sources specified in all terraform files in the directory specified with `-d` flag.

Terrascan would report violations for the terraform files in the modules as well.

**Comment by jdgoins** [comment]
Is support for git repo or Terraform Registry modules in this project's roadmap? 

Is there a way to direct the tool to ignore modules with unsupported sources? Most of my Terraform code points to some sort of remote module, which causes the tool to error out.
