### ISSUE TITLE
Allow structure output (Json)

### ISSUE THREAD

**Issue by AssafKatz3** [accurics/terrascan#252]
* terrascan version: N/A
* Python version: N/A
* Operating System: N/A

### Description

I want to integrate it with SonarQube, for it I need structure output - Json preferred, but anything that it machine readable will be fine.

**Comment by cesar-rodriguez** [comment]
Thanks for the suggestion. I agree this is something that we should add as an option.

**Comment by nightwatchcyber** [comment]
See also #119

**Comment by williepaul** [comment]
Hello, @nightwatchcyber, v1.0.0 now contains json/yaml support out of the box.
