### ISSUE TITLE
Adding terrascan to Homebrew

### ISSUE THREAD

**Issue by nightwatchcyber** [accurics/terrascan#293]
Is it possible to add terrascan as a homebrew and Chocolatey package?

See:
https://docs.brew.sh/Adding-Software-to-Homebrew
https://chocolatey.org/docs/create-packages

**Comment by williepaul** [comment]
Yep, these are currently in the works.

**Comment by bill-demo-eg** [comment]
Thanks we are looking forward to it

**Comment by chenrui333** [comment]
Hi Folks, I have proposed to add this tool into `homebrew-core`. https://github.com/Homebrew/homebrew-core/pull/60787

**Comment by kanchwala-yusuf** [comment]
Thank you @chenrui333!

**Comment by chenrui333** [comment]
np, my pleasure. :)
