### ISSUE TITLE
terrascan doesn't find violations in terraform files created using modules

### ISSUE THREAD

**Issue by rupeshphuyal** [accurics/terrascan#302]
* terrascan version: 1.0.0
* Operating System: Linux

### Descriptions

I created some terraform files using modules and some without using modules. I added some violations in both but terrascan found violations in the files created without using modules but no violations found in the files using modules. 

### What I Did

```
terrascan scan -t aws 
```

**Comment by piyushcom** [comment]
Hi @rupeshphuyal 

Thanks for reaching out! Currently Terrascan supports modules, but only when referenced locally. We do have plans to support outside modules very soon. Thank you for using Terrascan.

**Comment by rupeshphuyal** [comment]
@piyushcom 

I have this file: sgs.tf
resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = aws_vpc.main.id

  ingress {
    description = "TLS from VPC"
    from_port   = 5
    to_port     = 5
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_tls"
  }
}

terascan result: 

terrascan scan -t aws -f sgs.tf
results:
  violations:
  - rule_name: unknownPortOpenToInternet
    description: Unknown Port is exposed to the entire internet
    rule_id: AWS.SecurityGroup.NPS.High.1046
    severity: HIGH
    category: Network Ports Security
    resource_name: allow_tls
    resource_type: aws_security_group
    file: sgs.tf
    line: 1
  count:
    low: 0
    medium: 0
    high: 1
    total: 1

Now I have another file main.tf  which has dependency  to the module sg_default which is local as well

module "sg_default" {
  source = "./sg_default"
  sg_name = "sg-test"
  sg_description = "Security Group managed by Terraform"
  vpc_id = "vpc-26e8dc5c"
  
  ### Inbound rules ###
  inbound_rules = {
    "0" = [ "0.0.0.0/0", "5", "5", "TCP" ]
    "1" = [ "0.0.0.0/0", "443", "443", "TCP" ]
    "2" = [ "0.0.0.0/0", "1234", "4321", "UDP" ]
  }
  
  ### Outbound rules ###  
  outbound_rules = {
    "0" = [ "0.0.0.0/0", "0", "0", "-1" ]
  }

  ### Tags ###  
  tags = {
    Name = "${var.sg_name}"
    Project = "test"
  }
}

terrascan result: 
terrascan scan -t aws -f main.tf
results:
  violations: []
  count:
    low: 0
    medium: 0
    high: 0
    total: 0

It is not working even if the module is sourced locally. It should have displayed the violation of unknown port as well which didn't happen using the module. 

 violations:
  - rule_name: unknownPortOpenToInternet
    description: Unknown Port is exposed to the entire internet
    rule_id: AWS.SecurityGroup.NPS.High.1046
    severity: HIGH

**Comment by kanchwala-yusuf** [comment]
Hi @rupeshphuyal,

I was unable to reproduce the issue on my setup:

Here is what I tried:

Created a local module directory structure which looks like:
```sh
$ tree
.
├── main.tf
└── sg_default
    └── sgs.tf

1 directory, 2 files
```

main.tf:
```
provider "aws" {
  region = "us-east-1"
}

module "sgs" {
  source = "./sg_default"
}
```

sg_default/sgs.tf:
```
resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = aws_vpc.main.id

  ingress {
    description = "TLS from VPC"
    from_port   = 5
    to_port     = 5
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_tls"
  }
}
```

terrascan output:
```sh
$ terrascan scan -t aws
results:
  violations:
  - rule_name: unknownPortOpenToInternet
    description: Unknown Port is exposed to the entire internet
    rule_id: AWS.SecurityGroup.NPS.High.1046
    severity: HIGH
    category: Network Ports Security
    resource_name: allow_tls
    resource_type: aws_security_group
    file: sg_default/sgs.tf
    line: 1
  count:
    low: 0
    medium: 0
    high: 1
    total: 1
```

I am able to see the violations in the module directory structure as well.

Am I missing something here?

**Comment by rupeshphuyal** [comment]
@kanchwala-yusuf  you should not be hardcoding the values in modules. In your main.tf, values should be defined and in the modules, just make the variable. For example I have added port variable and supplied the input from main.tf. 

main.tf:

provider "aws" {
  region = "us-east-1"
}

module "sgs" {
  source = "./sg_default"
  port = 5
}
sg_default/sgs.tf:

variable "port" {
  default = []
}


resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = aws_vpc.main.id

  ingress {
    description = "TLS from VPC"
    from_port   = "${var.port}"
    to_port     = "${var.port}"
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_tls"
  }
}

**Comment by cesar-rodriguez** [comment]
I was able to replicate this issue with v1.0.0 of Terrascan. 

```
$ tree
.
├── main.tf
└── sg_default
    └── sgs.tf

1 directory, 2 files
```

```
cat main.tf 
provider "aws" {
  region = "us-east-1"
}

module "sgs" {
  source = "./sg_default"
  port   = 5
}
```

```
$ cat sg_default/sgs.tf 
variable "port" {
  default = []
}

resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = aws_vpc.main.id

  ingress {
    description = "TLS from VPC"
    from_port   = "${var.port}"
    to_port     = "${var.port}"
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "allow_tls"
  }
}
```

```
$ terrascan scan -t aws
2020-09-02T09:28:35.963-0400    error   v12/load-dir.go:88      failed to build unified config. errors:
<nil>: Failed to read module directory; Module directory /Users/therasec/programming/temp/sgs does not exist or cannot be read.
```

I built from source and seems like the issue is fixed, but there's an OPA warning
```
$ terrascan scan -t aws
2020-09-02T09:34:20.728-0400    warn    opa/engine.go:310       failed to run prepared query{rule 15 0 'portWideOpenToPublic' <nil>}
results:
  violations:
  - rule_name: unknownPortOpenToInternet
    description: Unknown Port is exposed to the entire internet
    rule_id: AWS.SecurityGroup.NPS.High.1046
    severity: HIGH
    category: Network Ports Security
    resource_name: allow_tls
    resource_type: aws_security_group
    file: sg_default/sgs.tf
    line: 5
  count:
    low: 0
    medium: 0
    high: 1
    total: 1
```

@kanchwala-yusuf Can you confirm?

**Comment by kanchwala-yusuf** [comment]
@cesar-rodriguez , @rupeshphuyal terrascan, currently, does have the ability to resolve variables or references. This feature is in pipeline and hence the terrascan is unable to report any violations.
