### ISSUE TITLE
Ability to add ignore comments to code

### ISSUE THREAD

**Issue by LogicNinja** [accurics/terrascan#310]
There doesn't appear to be the capability to ignore checks in terrascan.
Would it be possible to add the ability to add comments to code blocks to trigger terrascan to ignore specific error codes for that block?
Similar to how tfsec implements this capability 
https://github.com/liamg/tfsec#ignoring-warnings

**Comment by kanchwala-yusuf** [comment]
Hi @LogicNinja , 
Yes you are right, terrascan does not have the ability to ignore checks. We do have plans to add pre and post filters and processors to ignore checks and do other kinds of processing.
