### ISSUE TITLE
pre-commit hook?

### ISSUE THREAD

**Issue by sosimon** [accurics/terrascan#311]
Is there still a way to run terrascan with pre-commit? I noticed there was mention of an example `.pre-commit-config.yaml` in older docs but it's no longer mentioned anywhere now.

**Comment by cesar-rodriguez** [comment]
Hi @sosimon,

This is something that needs to be worked on The way the original .pre-commit-config.yaml file was written didn't work with v1.0.0 of Terrascan, so we had to remove it for now.

**Comment by cesar-rodriguez** [comment]
Submitted https://github.com/antonbabenko/pre-commit-terraform/pull/195 to address this for Terraform and planning on doing something similar in this repo to support all other IaC providers.

**Comment by amirbenv** [comment]
Thanks Cesar! can this be closed?

**Comment by cesar-rodriguez** [comment]
Closed via #953
