### ISSUE TITLE
Rule for github_repository seems to be wrongly placed under gcp

### ISSUE THREAD

**Issue by HorizonNet** [accurics/terrascan#325]
The rule `accurics.gcp.IAM.145` is currently located under [gcp](https://github.com/accurics/terrascan/commits/master/pkg/policies/opa/rego/gcp/github_repository), which isn't intuitive as it is targeting the GitHub provider and not GCP. It would be better to move its own policy set.

**Comment by williepaul** [comment]
@HorizonNet Agreed--the policy is written for that provider specifically. I think for now we may want to keep two copies of the rule, one in a provider-specific folder, and the original one. Ideally, probably it'll be helpful just to detect all providers used  and enable the corresponding policies by default.

**Comment by HorizonNet** [comment]
Added a first draft for the provider. Some points are probably still missing. Started by trying to simulate what was done for the gcp policies.
