### ISSUE TITLE
accurics.gcp.IAM.122 needs to take into account the new name for Uniform bucket-level access flag

### ISSUE THREAD

**Issue by ferrarimarco** [accurics/terrascan#329]
* terrascan version: `v1.1.0`
* Operating System: Ubuntu 20.04.1

### Description

Terrascan wrongly reports a violation of `accurics.gcp.IAM.122`.

The name of the property changed in the latest release of the Google Cloud Terraform provider, from `bucket_policy_only` to [uniform_bucket_level_access](https://www.terraform.io/docs/providers/google/r/storage_bucket.html#uniform_bucket_level_access).

**Comment by williepaul** [comment]
@ferrarimarco thanks for the heads up! We may end up locking the version for this (if possible) and create a similar rule for uniform_bucket_level_access. I'll check with the policy folks as we're still trying to gauge how best to maintain deprecated items.

**Comment by harkirat22** [comment]
The policy was already updated. Thus, closing this issue. 
Policy present [here ](https://github.com/accurics/terrascan/blob/master/pkg/policies/opa/rego/gcp/google_storage_bucket/uniformBucketEnabled.rego)
