### ISSUE TITLE
20MB binary file included in repo now

### ISSUE THREAD

**Issue by salexpdx** [accurics/terrascan#364]
* terrascan version: n/a
* Operating System:n/a

### Description

It looks like on the 1.0 update (https://github.com/accurics/terrascan/pull/284) that a 20MB binary file slipped it and is now in cmd/terrascan/terrascan It seems like this should be removed.  It's probably too late to clean up history and reduce the repo size, but at least avoiding having it checked out on the mainline branch seems like a good cleanup. 

### What I Did

```
MacBook-Pro:terrascan user$ file cmd/terrascan/terrascan
cmd/terrascan/terrascan: Mach-O 64-bit executable x86_64
MacBook-Pro:terrascan user$ ls -l cmd/terrascan/terrascan
-rwxr-xr-x  1 user  staff  20938316 Oct 26 11:08 cmd/terrascan/terrascan
```

**Comment by cesar-rodriguez** [comment]
Good catch. Thanks!
