### ISSUE TITLE
How to ignore a rule?

### ISSUE THREAD

**Issue by jgeurts** [accurics/terrascan#367]
Hi,

How do I ignore a specific rule from running? Is there a magic comment I can put in my .tf file to ignore a rule in one specific location?

For example, I have an iam user that I would like to ignore rule programmaticAccessCreation (AWS.IamUser.IAM.High.0391):

```tf
resource "aws_iam_user" "example" {
  name = "example"
}

# terrascan-ignore AWS.IamUser.IAM.High.0391
resource "aws_iam_access_key" "example" {
  user = aws_iam_user.example.name
}
```

**Comment by cesar-rodriguez** [comment]
Hi  @jgeurts,

We currently don't support that. 

A workaround is to remove that policy from ~/.terrascan/pkg/policies/opa/rego/aws/aws_iam_user_login_profile/AWS.Iam.IAM.High.0391.json, but that would affect your local installation. You can also use the `-p` flag to specify a directory with the specific OPA policies you want for a specific scan (the directory needs to include both the .json and .opa files).

**Comment by RafaAguilar** [comment]
@jgeurts While it gets implemented (or discarded), for simplistic scenarios we could add an snippet to pipelines and deploy scripts something that can mimic Ignore behavior externally.

An example is in the following gist.

https://gist.github.com/RafaAguilar/5872e9579c308f0209290001496c1a2b

This can also give Terrascan maintainers a way to evaluate how this feature should behave or if whether should exist or no.
