### ISSUE TITLE
Add --severity options

### ISSUE THREAD

**Issue by myugan** [accurics/terrascan#392]
I've explore `terrascan` tools to filter an output by severity level but can't found it, it will be good if the tools can filter an output by risks and possible to embeded into CI/CD pipeline.

**Comment by cesar-rodriguez** [comment]
Thanks for the suggestion @myugan. As a workaround while this gets implemented, you can use a tool like [jq](https://stedolan.github.io/jq/) and filter the json output like this:

``` bash
terrascan scan -o json | jq '.results.violations[] | select(.severity=="HIGH")'
```
