### ISSUE TITLE
Improve test coverage for k8s

### ISSUE THREAD

**Issue by dev-gaur** [accurics/terrascan#400]
### Description

I feel a dire need for making test coverage for k8s iac-provider as robust as possible, maybe even with special focus.
We have introduced support for helm and kustomize scanning and both those iac-provider implementations depend on the k8s iac-provider implement up to a significant extent. Therefore, its a no brainer to improve to make the k8s provider as robust as possible to keep a strong foundation.

**Comment by amirbenv** [comment]
@dev-gaur can this be closed
