### ISSUE TITLE
Improved Documentation

### ISSUE THREAD

**Issue by rajagopalananjana** [accurics/terrascan#416]
* CI \ CD
* More Example Usages
* Begin Remediation Guide

**Comment by dhartford** [comment]
I agree with more applied example usage, particularly for first time usage.

running terraform init, followed by terraform plan, before running the terrascan seems to make a big difference and only found that through other bug reports.

The new 'remote module' support for TF seems to be in place, but isn't clear unless you happened to have check tickets/merge requests.

Remote module support may have an:
"invalid active developer path....missing xcrun" on mac, fix would be:
xcode-select --install     
sudo xcode-select --reset

**Comment by amirbenv** [comment]
We've updated our README.md and our docs site since this issue was posted. 
There are definitely more improvements we can make. 
Anything in particular we should focus on? @dhartford, and anyone else!

**Comment by kanchwala-yusuf** [comment]
We have improved our documentation since this issue was reported. Closing this one for now. 

But if there is anything specific that is required from documentation perspective, please feel free to open a new issue.

Thank you!
