### ISSUE TITLE
Improve description for init command

### ISSUE THREAD

**Issue by dev-gaur** [accurics/terrascan#461]
the word `init` already gives away that initiatization will occur. perhaps we add a bit more verbore description and tell broadly tells what exactly happends.i.e., policy files being cached locally.

![image](https://user-images.githubusercontent.com/7551036/103908013-02a76a80-5128-11eb-800f-26d1caf49183.png)

**Comment by kanchwala-yusuf** [comment]
Hi @dev-gaur ,

```bash
➜  terrascan git:(master) ./bin/terrascan init -h
Terrascan

Initializes Terrascan and clones policies from the Terrascan GitHub repository.

Usage:
  terrascan init [flags]

Flags:
  -h, --help   help for init

Global Flags:
  -c, --config-path string   config file path
  -l, --log-level string     log level (debug, info, warn, error, panic, fatal) (default "info")
  -x, --log-type string      log output type (console, json) (default "console")
  -o, --output string        output type (human, json, yaml, xml) (default "human")
```

The help for `init` command itself gives a more information about the `init` command.

Do you think, this would suffice?

**Comment by dev-gaur** [comment]
Yeah I think this much is good. I'll send a PR to update the description for `init` command in `terrascan -h`

**Comment by dev-gaur** [comment]
Or it can be a `good first issue` :D
