### ISSUE TITLE
Rule severity field output should be case insensitive

### ISSUE THREAD

**Issue by williepaul** [accurics/terrascan#483]
* terrascan version: 1.2
* Operating System: all

### Description

When scanning a repo, if the severity field is not all caps (HIGH|MEDIUM|LOW), when violations are output, the color of the severity field does not show up. The compare should be case-insensitive, OR we can normalize the severity field.

### What I Did

```
terrascan scan -d [dir]
```

**Comment by rijusougata13** [comment]
can you explain a little bit more.what is the main issue here?

**Comment by williepaul** [comment]
Sure--in the policy rule.json files, the severity field is either marked as HIGH, MEDIUM, or LOW. However, in some policies, lowercase values are used, or only the first letter are capitalized. Because of that, when scanning terraform files that have violations, the color of the output, instead of being red, green, yellow, ends up displaying as gray for those policies. I suspect the colorizer is just not converting the severity field to all-lower or all-upper prior to comparing.
