### ISSUE TITLE
Custom Variable Validation no longer experiemental in 0.13

### ISSUE THREAD

**Issue by tarunngc** [accurics/terrascan#500]
* terrascan version: 1.2.0
* Operating System: Windows 10

### Description

Trying to run terrascan on AzureRM Terraform configuration. The following message continues to show up even though Custom Variable Validation is no longer experimental in 0.13 (https://www.hashicorp.com/blog/custom-variable-validation-in-terraform-0-13):

```
Experimental feature "variable_validation" is active; Experimental features are subject to breaking changes in future minor or patch releases, based on feedback.

If you have feedback on the design of this feature, please open a GitHub issue to discuss it., and 1 other diagnostic(s)
```

### What I Did

```
terrascan init
terrascan scan
```

**Comment by kanchwala-yusuf** [comment]
Hey @tarunngc,
We have added support for terraform 0.13.x & 0.14.x in our latest terrascan release `v1.3.0`. Can you please try it out and see this issue still exists?

**Comment by tarunngc** [comment]
Hi @kanchwala-yusuf 

I tried `v1.3.0` and the error no longer occurs as expected. Thanks for the quick response and help.
