### ISSUE TITLE
Tag container image with release version

### ISSUE THREAD

**Issue by kanchwala-yusuf** [accurics/terrascan#504]
* terrascan version: v1.3.0
* Operating System:

### Description
The release process should create a docker container with release version tag.
It becomes easy for the users to download the docker image for a specific terrascan release.

**Comment by rahulchheda** [comment]
Hey @kanchwala-yusuf , I would like to pick this up. Btw, being new to this project might take me a bit of a time to get started. Hope you don't mind that. Thanks.

**Comment by kanchwala-yusuf** [comment]
Hey @rahulchheda,
Thank you for your interest! 

Sure, you can give this one a try. You would need to make changes in our release workflow.

Let me know if you need any help here :)

**Comment by rahulchheda** [comment]
Hey @kanchwala-yusuf , as part of this commit: https://github.com/accurics/terrascan/commit/a086a6529199ef28e42d696453316e1ff61c854a, I can see that we are already releasing with the latest tag on docker hub. And checked the `release` job too, it doesn't really print the `tag` it it releasing, but seems to be able to push into: https://github.com/accurics/terrascan/runs/1729277223?check_suite_focus=true
Needed more context on this issue. :)

**Comment by kanchwala-yusuf** [comment]
Hey @rahulchheda,
You are right we are publishing the docker images with `latest` tag, but not with release version tag. And we want to publish with release version tag as well. Because `latest` tag can would be overwritten whenever a newer release comes out.

So, terrascan release version are the same as github tags. I am wondering, there should be a way in GithubActions to figure out the github tag (something like `${{ github.event.release.tag_name }}`?). Once we get the release version, then it should be just about tagging the created docker image with the correct tag.

**Comment by rahulchheda** [comment]
We are getting the latest github relrease tag, and then pushing it into docker hub: https://github.com/accurics/terrascan/blob/8e3e41b390e59c5a0fe06003425f57ba1506a757/scripts/docker-push-latest-tag.sh#L10.

**Comment by rahulchheda** [comment]
Let me make sure this works as expected.

**Comment by kanchwala-yusuf** [comment]
@rahulchheda , 
I think, it's working and already in place. Just saw on the terrascan docker hub that the image with release version was pushed.

The below command worked fine:
```bash
 docker pull accurics/terrascan:1.3.0
```

**Comment by kanchwala-yusuf** [comment]
This issue was opened in error. This issue was already resolved when https://github.com/accurics/terrascan/issues/398 was resolved.

**Comment by kanchwala-yusuf** [comment]
Thank you @rahulchheda , for helping out! 

Closing this for now.
