### ISSUE TITLE
terrascan init should download new policies

### ISSUE THREAD

**Issue by kanchwala-yusuf** [accurics/terrascan#521]
* terrascan version: v1.3.1
* Operating System: all

### Description
`terrascan init` should download the latest policies from github repository. Currently, `terrascan init` downloads the policies only once, and subsequently invocations of `terrascan init` do not refresh policies.

**Comment by rahulchheda** [comment]
@kanchwala-yusuf Would like to pick this up!

**Comment by kanchwala-yusuf** [comment]
Thanks @rahulchheda, welcome your contributions! Let me know if you need any help on this one?

**Comment by kanchwala-yusuf** [comment]
Hey @rahulchheda , Did you get a chance to look at this issue?

**Comment by rahulchheda** [comment]
Hey Yusuf, I have started with this task, and will create a work in progress PR soon.

**Comment by dev-gaur** [comment]
Hey @kanchwala-yusuf @rahulchheda sorry I had to merge a quick fix for this issue as it is a critical bug. @rahulchheda , if you could try to optimize the way we download policies, that'd be awesome!

**Comment by rahulchheda** [comment]
No problem @dev-gaur, and sure I will take a stab at it.

**Comment by dev-gaur** [comment]
@rahulchheda https://github.com/accurics/terrascan/issues/535

**Comment by dev-gaur** [comment]
@rahulchheda https://github.com/accurics/terrascan/issues/535

**Comment by dev-gaur** [comment]
@rahulchheda https://github.com/accurics/terrascan/issues/535
