### ISSUE TITLE
optimize policy download process in `terrascan init`

### ISSUE THREAD

**Issue by dev-gaur** [accurics/terrascan#535]
Currently the policy downloading flow is :

1. Download latest terrascan repo in the local machine and checkout to master branch in a temp location.
2. After the successful download, move the newly downloaded repo to the base policy path, overriding the existing repo.

There's ample scope for optmization here. We can leverage `git diff` and `git pull` for this and download the parts that are outdated or missing. Or save ourselves from downloading the policies if the existing local repo is up to date.

@jlk @patilpankaj212 may have more points to add.

**Comment by rahulchheda** [comment]
What about using `go-git` library?

**Comment by dev-gaur** [comment]
yes, I meant for applying the `git diff` & `git pull` equivalent logic using the go-git library.

**Comment by rahulchheda** [comment]
I think we would be able to achieve that even with `git pull` as it will take care of just adding new commits, rather than cloning again. And go-git might just support it (ref: https://pkg.go.dev/github.com/go-git/go-git/v5#Worktree.Pull)

**Comment by patilpankaj212** [comment]
@rahulchheda have a look at refreshPolicies function here: https://github.com/patilpankaj212/terrascan/blob/0c294e9b8626591bc9f8f72ba931bc90939c6153/pkg/initialize/run.go, may be you can improve upon this?

**Comment by rahulchheda** [comment]
> @rahulchheda have a look at refreshPolicies function here: https://github.com/patilpankaj212/terrascan/blob/0c294e9b8626591bc9f8f72ba931bc90939c6153/pkg/initialize/run.go, may be you can improve upon this?

This looks really great! Seems like it handles all the cases that I thought of.

**Comment by kanchwala-yusuf** [comment]
Closing this for now. Please reopen if required.
