### ISSUE TITLE
AWS.CloudFront.Network Security.Low.0568 Doesn't allow skipping due to space in filename

### ISSUE THREAD

**Issue by brainthee** [accurics/terrascan#549]
* terrascan version: v1.3.1
* Operating System: Ubuntu 20.10

### Description

When defining a `aws_cloudfront_distribution` resource, one of the policies can not be skipped due to a space in it's filename (and therefore I assume failing the regex check for the `#ts` lines). 

### What I Did

We have a aws_cloudfront_distribution resource that defines no geo restrictions as restrictions are handled further down the chain:

```
  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }
```

So the policy failing is correct, we just can't skip it due to the space in the file here: https://github.com/accurics/terrascan/blob/master/pkg/policies/opa/rego/aws/aws_cloudfront_distribution/AWS.CloudFront.Network%20Security.Low.0568.json

**Comment by amirbenv** [comment]
Thanks for reporting. We'll get it fixed soon!

**Comment by jerusdp** [comment]
Similar problem in aws.api.gateway.stage set with space in the file name for the JSON files.

**Comment by harkirat22** [comment]
@jerusdp thanks for reporting. Going to get it fixed
