### ISSUE TITLE
Issue on Azure DevOps Agents since 1.3.2 : failed to initialize terrascan

### ISSUE THREAD

**Issue by alex-3sr** [accurics/terrascan#561]
* terrascan version: 1.3.3
* Operating System: Windows Azure DevOps Agent Hosted

### Description

Until 1.3.1, we didn't have any issue, and since 1.3.2 all pipelines failed with warning. The issue still present with 1.3.3.
It seem that the issue is coming with the last fix about downlaod policies on 1.3.2 https://github.com/accurics/terrascan/issues/521

When we add debug log, we can see that Terrascan are unable to init because can't install policies. I think it's because the target folder is write protected, but on Hosted Azure Devops Agent we can't change it.

So, I'm a bit confused if it's a limitation of Azure DevOps and at same time like it's worked until 1.3.1 if last update can break the usage of terrascan on Azure DevOps. Is it really an issue ? BTW in anycase, works perfectly locally on my Windows Computer. Maybe it's just be an improvement that we need for still use in Azure DevOps by using an extra arguments for say where policies need to be downloaded (on a non protected write folder) for workaround, but I didn't find a way to add this extra args.

Thanks for your help/advice, Regards
Alex

### What I Did

```
terrascan.exe scan -t azure -i terraform --iac-version v14 -o json
```

Here the error log that I can have with just a terrascan init on Azure DevOps
```
2021-02-19T19:46:40.347Z	debug	config/global.go:59	global config env variable is not specified
2021-02-19T19:46:40.380Z	debug	initialize/run.go:40	initializing terrascan
2021-02-19T19:46:40.380Z	debug	initialize/run.go:60	downloading policies
2021-02-19T19:46:40.380Z	debug	initialize/run.go:69	cloning terrascan repo at C:\Users\VSSADM~1\AppData\Local\Temp\terrascan-756921911
2021-02-19T19:46:50.958Z	error	cli/init.go:42	failed to initialize terrascan. error : failed to install policies to '/.terrascan'. error: 'rename C:\Users\VSSADM~1\AppData\Local\Temp\terrascan-756921911 /.terrascan: The system cannot move the file to a different disk drive.'
```

**Comment by amirbenv** [comment]
Hi @alex-3sr! Thanks for the report. Will follow up soon

**Comment by dev-gaur** [comment]
Hey @alex-3sr , we're working on a fix for this issue. gonna release with a patch soon.

meanwhile, could you try specifying the policy path in the [config file](https://docs.accurics.com/projects/accurics-terrascan/en/latest/getting-started/usage/#config-file) for now? let us know if that works for you.

Also, could you let us know if there's any HOME environment variable set on the host machine?

**Comment by dev-gaur** [comment]
Could you try this terrascan [binary](https://github.com/dev-gaur/terrascan/raw/windows_binary/bin/terrascan.exe) (compiled for windows) in your pipeline and see if you face the same issue?
