### ISSUE TITLE
Add `/go/bin` to the PATH variable in Docker image

### ISSUE THREAD

**Issue by sfuerte** [accurics/terrascan#577]
* terrascan version:
docker.io/accurics/terrascan@sha256:cf459ae515849f2c004308c1a924958c3f92b121c94d64dcfac3849ce09b00b3

* Operating System:
Docker

### Description

When used in a pipeline, need to add full path otherwise it fails with an error. Would be logically if the Docker image's `PATH` environment variable had `/go/bin` in it. 

### What I Did

```
Images used:
    build : docker.io/accurics/terrascan@sha256:cf459ae515849f2c004308c1a924958c3f92b121c94d64dcfac3849ce09b00b3

+ terrascan version
/opt/atlassian/pipelines/agent/tmp/shellScript17173005529052170318.sh: line 4: terrascan: not found
Build teardown

```

![image](https://user-images.githubusercontent.com/16941995/109732980-73449380-7b7b-11eb-9dfb-1002126352d2.png)

**Comment by kanchwala-yusuf** [comment]
Hi @sfuerte,

I just tried to reproduce the issue that you reported with a terrascan docker image for release v1.4.0 and I was not sure if I was able to reproduce this issue

```sh
➜  ~ docker pull accurics/terrascan:1.4.0
1.4.0: Pulling from accurics/terrascan
df20fa9351a1: Already exists
febb8affd2d2: Pull complete
0f56eae05a73: Pull complete
Digest: sha256:02dc24ef3dc32338a7f2527961e5b83dc817b12c68028bff5e79f358535bae70
Status: Downloaded newer image for accurics/terrascan:1.4.0
docker.io/accurics/terrascan:1.4.0

➜  ~ docker run --rm accurics/terrascan:1.4.0 version
version: v1.4.0
```

Does this help? or is there something else that you are looking for?

**Comment by seancallaway** [comment]
This should be a pretty quick fix. I'd be interested in adding this.

**Comment by kanchwala-yusuf** [comment]
Hey @seancallaway , 
Sure please go ahead

Thank you for taking this initiative!
