### ISSUE TITLE
Terrascan API server's file scan doesn't work for k8s yaml files

### ISSUE THREAD

**Issue by patilpankaj212** [accurics/terrascan#584]
* terrascan version: 1.3.3
* Operating System: Mac OS X 10.15.7

### Description

k8s yaml file scan fails with API server.

### What I Did

1. launch terrascan in server mode
2. send a request to scan a k8s yaml file
3. received a internal server error status back (attached screenshot)
<img width="846" alt="apiServer_file_scan_k8s_issue" src="https://user-images.githubusercontent.com/26894287/109998958-c400eb80-7d37-11eb-917f-ecc37f3a76aa.png">

**Comment by jlk** [comment]
This should be resolved with #592. Closing
