### ISSUE TITLE
Invalid categories not being validated from config file

### ISSUE THREAD

**Issue by kanchwala-yusuf** [accurics/terrascan#594]
* terrascan version: v1.4.0
* Operating System: all

### Description
When invalid categories are specified in the terrascan config toml file, these invalid category types are not validated resulting in incorrect terrascan output. Hence, It is necessary to validate the input category types from config file.

**Comment by dev-gaur** [comment]
@kanchwala-yusuf , I just checked, they're actually being validated. 

I guess you may have used

```
[categories]
    list = ["test"]
```

instead of 

```
[category]
    list = ["test"]
```

it's an easy gotcha. we should document this.
