### ISSUE TITLE
Terrascan not able to read modules within a subdirectory

### ISSUE THREAD

**Issue by jlunaq** [accurics/terrascan#600]
terrascan v1.3.3
MacOS Catalina 10.15.7

Hey there ,

I'm currently working with terraform modules hosted on github, I found that terrascan is able to read the modules when they are in the root directory.
However I found an issue with a module which is in a subdirectory, like this:

`source = "git@github.com:company/module.git//modules/base?ref=v2.0.0"`

In this particular case is where I'm getting this error

`<nil>: Failed to read module directory; Module directory /Users/jluna/my-project/git@github.com:company/module.git/modules/roles does not exist or cannot be read.`

Thanks in advance
- Jorge

**Comment by jlunaq** [comment]
Hello, any update

**Comment by dev-gaur** [comment]
@jlunaq is that module (inside the subdirectory) being consumed by the root directory module ?

**Comment by jlunaq** [comment]
Yep, sorry I forgot to mention that.

From the root module I am consuming the other module like this.

```
module "project_owner_role" {
  source = "../roles"

  ...
}
```

Note that I'm using a relative path `../roles` not sure how this could be affecting the way terrascan fetches the modules

**Comment by djsly** [comment]
I'm having the same issues I think where the root module is consuming child module from remote sources 

```
✖ terrascan scan
2021-03-18T13:03:39.934-0400    error   commons/load-dir.go:121 failed to build unified config. errors:
<nil>: Failed to read module directory; Module directory /Users/sylvain_boily/git/gitlab/core-tech/infra/deployments/sandboxes/azure-sly-eastus/https:/<hostname>/artifactory/xinfra-tf/release/azure-xinfra/azure-xinfra-v0.13.2-RC4.tar.gz/https:/<hostname>/artifactory/xinfra-tf-local/release/tf-kubernetes-artifactory-frontend/tf-kubernetes-artifactory-frontend-v2.6.2.tar.gz/backend-endpoints does not exist or cannot be read.
```

**Comment by d2k-klin** [comment]
same thing here
Windows 10
terrascan v1.4.0

module "db_dev" {
  source             = "terraform-aws-modules/rds/aws"
  version            = "2.26.0"
.
.
.
########output:
terrascan scan -t aws -i terraform
2021-03-19T23:28:50.589+0100    error   commons/load-dir.go:121 failed to build unified config. errors:
<nil>: Failed to read module directory; Module directory C:\IaC\terraform-aws-modules\rds\aws\modules\db_instance does not exist or cannot be read., and 4 other diagnostic(s)

2021-03-19T23:28:50.841+0100    error   cli/run.go:107  scan run failed{error 26 0  failed to build terraform allResourcesConfig}
