### ISSUE TITLE
Terrascan not found policy id

### ISSUE THREAD

**Issue by artur-carvalho** [accurics/terrascan#601]
* terrascan version: 1.3.1
* Operating System: Ubuntu 20.04

### Description

We have a terraform pipeline and the first step is the Terrascan, because of some internal decisions we skip the rules:
-  accurics.azure.NS.161 - Ensure that Azure Virtual Network subnet is configured with a Network Security Group
-  accurics.azure.NS.272 - Ensure that Azure Resource Group has resource lock enabled

This is my .toml config file
```
[rules]

    skip-rules = [
        "accurics.azure.NS.161",
        "accurics.azure.NS.272",
    ]
```

And then I run this script to run the Terrascan:

```
curl --location https://github.com/accurics/terrascan/releases/download/v1.3.1terrascan_1.3.1_Linux_x86_64.tar.gz --output terrascan.tar.gz

tar -xvf terrascan.tar.gz

sudo install terrascan /usr/local/bin    

terrascan scan -c ../.ci/terrascan-config.toml -t azure .
```

This was working until yesterday, for some reason now we are receiving this error:
```
skip rule id: accurics.azure.NS.161 not found in policy path: /home/vsts/.terrascan/pkg/policies/opa/rego/azure
skip rule id: accurics.azure.NS.272 not found in policy path: /home/vsts/.terrascan/pkg/policies/opa/rego/azure
```

I have uninstalled and installed again, tried to change the rule id to another name,  removed the ~/.terrascan file and run terrascan init and still the same error.

Do you have any idea about it? Did the rule's ID have been updated? I checked the documentation and apparently are the same.

**Comment by amirbenv** [comment]
Hi @artur-carvalho.
Thanks for flagging this. We will have a fix soon. We updated our policies, and a breaking change found its way in. Will revert.

**Comment by amirbenv** [comment]
@artur-carvalho can you run terrascan init and try again?

**Comment by artur-carvalho** [comment]
Hi @amirbenv,

Thanks for the quick response,

It is working again, thank you!
