### ISSUE TITLE
failed to initialize terrascan. error : failed to install policies

### ISSUE THREAD

**Issue by christophetd** [accurics/terrascan#614]
* terrascan version: v1.4.0
* Operating System: Ubuntu 18.04 LTS

### Description

Running `terrascan init` or `terrascan scan` yields the following output:

```
2021-03-14T11:00:42.987+0100    error   cli/init.go:42  failed to initialize terrascan. error : failed to install policies to '/home/christophetd/.terrascan'. error: 'rename /tmp/terrascan-522112316 /home/christophetd/.terrascan: invalid cross-device link'
```

### What I Did

- Creating `/home/christophetd/.terrascan` manually did not fix the issue. It actually seems `terrascan init` removes it.
- Manually cloning https://github.com/accurics/terrascan.git to ~/.terrascan seems to fix the issue

**Comment by amirbenv** [comment]
Thanks for reporting. We are working on improvements for the init command.

**Comment by dev-gaur** [comment]
@christophetd hey. did you run this inside a container ? if yes, mind sharing the oci image or the Dockerfile  ?

**Comment by dev-gaur** [comment]
@christophetd could you please mention the exact steps to replicate? I tested `terrascan init` inside an ubuntu:18.04 container. It seemed to work fine.

**Comment by tiagocosta-viavarejo** [comment]
I've the same issue.
That work only into containers.

I've tried to compile and I got the same error.

tested into:
- Debian 10
- Fedora 33
- Fedora 32

**Comment by christophetd** [comment]
I ran it on my main machine, not inside a container. I posted the exact commands I ran
