### ISSUE TITLE
Terrascan does not support to download modules via SSH

### ISSUE THREAD

**Issue by sachinar** [accurics/terrascan#621]
* terrascan version: 1.4.0
* Operating System: docker image (accurics/terrascan:1.4.0 )

### Description

We are trying to use terrascan  for our terraform repo. We are downloading modules through ssh.

### What I Did
    - /go/bin/terrascan init
    - /go/bin/terrascan scan --use-colors t .
   
```
2021-03-15T09:52:56.710Z	error	commons/load-dir.go:109	failed to download remote module "git::ssh://git@gitlab.com/global-terraform0.12-modules.git//tiller". error: 'error downloading 'ssh://git@gitlab.com/global-terraform0.12-modules.git': /usr/bin/git exited with 128: Cloning into '/tmp/j8ipfe'...
```

**Comment by sachinar** [comment]
Hi Team,

I tried to install openssh it worked for me.

Below is the Dockerfile for same
```
FROM accurics/terrascan:1.4.0
ENTRYPOINT []
USER root 
RUN apk add --no-cache openssh
WORKDIR /home/terrascan
USER terrascan
RUN mkdir -p .ssh && chown -R terrascan:terrascan .ssh
CMD ["server", "--log-type", "json"]

```
Can you guys just add openssh to docker image?

Created docker image can be downloaded with this name and tag.
`sachinar/terrascan:1.4.0`

**Comment by kanchwala-yusuf** [comment]
Thanks @sachinar for your contribution!

**Comment by sachinar** [comment]
@kanchwala-yusuf Please share the image tag for this PR.
