### ISSUE TITLE
terrascan using absolute path for "source" value of resource

### ISSUE THREAD

**Issue by hapyharshit** [accurics/terrascan#642]
* terrascan version: latest
* Operating System: all

### Description

when we generate normalize json, each resource has "source" property which is the location of the resource in the particular file.
this was working fine earlier, but now its using absolute path, which is a problem if I run terrascan in a VM, I will have wrong location of the file.

### What I Did

```
terrascan scan -t k8s -i k8s--config-only -o json
```

**Comment by kanchwala-yusuf** [comment]
Hi @hapyharshit , 
Thank you for reporting this. It seems that this is an issue only with `kubernetes` IaC. The behavior seems to be correct for other iac types like terraform, helm.
