### ISSUE TITLE
Rework release pipeline to work with cgo

### ISSUE THREAD

**Issue by jlk** [accurics/terrascan#693]
For release 1.5, we have added functionality that requires compiling go code with `CGO_ENABLED=1`. This breaks our ability to cross-compile with [goreleaser](https://goreleaser.com/).

Need to come up with a new process/GH workflow to do a cross-platform release in an automated fashion.

**Comment by amirbenv** [comment]
next release version is 1.5

**Comment by jlk** [comment]
Fixed, thx. Working with tag 1.15 on a private test repo... 🤪
