### ISSUE TITLE
tfplan should use resource address for id field

### ISSUE THREAD

**Issue by xortim** [accurics/terrascan#702]
* terrascan version: 1.5.0
* Operating System: macOS

### Description

I'm attempting to identify which resources are in violation of policies. Being able to identify resources in the same or similar way as Terraform's own output and internal representation of these resources would be helpful. So instead of `null_resource.this` we would get `module.example.null_resource.this`. It would be helpful to have a better understanding of how the different resource representations within the plan file are merged by terrascan.

### What I Did

`./main.tf`
```hcl
resource "null_resource" "this" {
  provisioner "local-exec" {
    command = "echo 'Hello'"
  }
}
```

`./example/main.tf`
```hcl
module "example" {
  source "../"
}
```

`terrascan scan -i tfplan --config-only -o json`
```json
{
  "null_resource": [
    {
      "id": "null_resource.this",
      "name": "this",
      "source": "",
      "line": 0,
      "type": "null_resource",
      "config": {
        "triggers": null
      },
      "skip_rules": null
    }
  ]
}
```

In the plan file, these have the desired attribute under `planned_values` and `resource_changes`:
```json
{
  "format_version": "0.1",
  "terraform_version": "0.14.10",
  "planned_values": {
    "root_module": {
      "child_modules": [
        {
          "resources": [
            {
              "address": "module.example.null_resource.this",
...
  "resource_changes": [
    {
      "address": "module.example.null_resource.this",
...
```

**Comment by kanchwala-yusuf** [comment]
Hi @xortim ,
I have tried to fix this issue as part of #825, please let me know if this helps! You can try out the fix in the latest `master` or wait for a release.

Thank you!
