### ISSUE TITLE
Broken brew install on ubuntu

### ISSUE THREAD

**Issue by ItsSpat** [accurics/terrascan#704]
$~/terrascan-test/terrascan$ brew install terrascan==> Downloading https://ghcr.io/v2/linuxbrew/core/go/manifests/1.16.3_1
Already downloaded: /home/acqa1/.cache/Homebrew/downloads/8d4559c979577332d0d6bf268f396bbb087a73e79ba35dd1b78938f120c03e64--go-1.16.3_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/go/blobs/sha256:5897db2f754dd7889b7ed262db7fc2b5c1d43e4148d66f1c5fbedb16c4e4fa55
Already downloaded: /home/acqa1/.cache/Homebrew/downloads/464da5eb5b3107404242441584f51bab39317fcff93daf8aa85ae81bcd4f6abf--go--1.16.3_1.x86_64_linux.bottle.tar.gz
==> Downloading https://github.com/accurics/terrascan/archive/v1.5.0.tar.gz
==> Downloading from https://codeload.github.com/accurics/terrascan/tar.gz/v1.5.0
######################################################################## 100.0%
_**Error: SHA256 mismatch
Expected: fee8fc66a76e13e5a2f211b58bdc73745e0b97b29dcb272504fca5edd3c47b5c
  Actual: e969960d9748e50125359097f5004c34ccf72e638dd06d10204a62468d57b260
    File: /home/acqa1/.cache/Homebrew/downloads/71759663e77b1616452dc5f244634fc4dc1a8cbfe2718a601941bf9d185b2de3--terrascan-1.5.0.tar.gz
To retry an incomplete download, remove the file above.**_

**Comment by theseanodell** [comment]
#701

**Comment by jlk** [comment]
closing duplicate.
