### ISSUE TITLE
Error with finding Enable AWS CloudWatch Logs for APIs

### ISSUE THREAD

**Issue by gaberamosfc** [accurics/terrascan#730]
* terrascan version: v1.5.0
* Operating System: macOS Catalina - 10.15.5

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

I am attempting to resolve the finding:
Enable AWS CloudWatch Logs for APIs

```
resource "aws_api_gateway_stage" "main" {
...
  stage_name    = var.stage_name
  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.apigw.arn
    format          = "..."
  }
...
}

resource "aws_cloudwatch_log_group" "apigw" {
  name              = "API-Gateway-Execution-Logs_${aws_api_gateway_rest_api.main.id}/${var.stage_name}"
...
}
```

### What I Did

When I change terraform resource name of aws_cloudwatch_log_group to "main" to match the same resource name of the 'aws_api_gateway_stage' the error is resolved.

```
resource "aws_api_gateway_stage" "main" {
  stage_name    = var.stage_name
  access_log_settings {
    destination_arn = aws_cloudwatch_log_group.apigw.arn
    format          = "..."
  }
}

resource "aws_cloudwatch_log_group" "main" {
  name              = "API-Gateway-Execution-Logs_${aws_api_gateway_rest_api.main.id}/${var.stage_name}"
...
}

```

**Comment by gaberamosfc** [comment]
Not sure if this is an issue, but I will close it.

**Comment by yermulnik** [comment]
Just hit this too and setting same name for both resources (not `main` though) didn't fix the issue.
