### ISSUE TITLE
Out of the box handling of certificates in helm charts for terrascan in Server mode 

### ISSUE THREAD

**Issue by amirbenv** [accurics/terrascan#756]
Currently, helm chart created for terrascan only accepts TLS certs from user provided files. Creating and managing certs can be quite a task for terrascan users. So there should be a way to auto generate self signed TLS certs and start terrascan in server mode using these certs.

**Comment by dev-gaur** [comment]
@amirbenv @kanchwala-yusuf what's the deliverable here exactly? do you want a ready to use shell script ?
