### ISSUE TITLE
Can't skip rules with underscore

### ISSUE THREAD

**Issue by alexgoedeke** [accurics/terrascan#856]
* terrascan version: v1.6.0
* superlinter version: v4.0.2
* Operating System: Ubuntu 20.04.2 LTS

### Description

I'm using terrascan within the superlinter github action and figured out that it is not possible to skip rules with an userscore (e.g. AC_AWS_049). 

### What I Did

Use the superlinter github action

**Comment by kanchwala-yusuf** [comment]
Hey @alexgoedeke , 
Can you please let us know how are you trying to skip rules? Are you using `--skip-rules` with the CLI or inline comments in your IaC code?

**Comment by alexgoedeke** [comment]
@kanchwala-yusuf I use the inline comments

**Comment by kanchwala-yusuf** [comment]
Hey @alexgoedeke , 
I believe #843 should fix this problem. Thanks :)
