### ISSUE TITLE
Kustomize support says v3 but is actually v4

### ISSUE THREAD

**Issue by williepaul** [accurics/terrascan#891]
* terrascan version: 1.7.0
* Operating System: all

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Kustomize support uses the latest libraries, and Kustomize has bumped their version to v4 (~Feb). However, the support list in the help screen still lists v3 as the supported version. Preferably, Terrascan should support both v3 and v4, as there are some breaking changes in v4 and many folks would still be using v3.

### What I Did

- Run terrascan help scan
Notice that the only valid version for kustomize is "v3", but this is incorrect; the libraries currently imported now are supporting v4.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by cesar-rodriguez** [comment]
Addressed with #932
