### ISSUE TITLE
Link to docks in README 

### ISSUE THREAD

**Issue by ah-f3** [accurics/terrascan#944]
### Description

Link on the Docker section of the README (https://github.com/accurics/terrascan/blob/master/README.md#docker-image) 

takes you to https://docs.accurics.com/projects/accurics-terrascan/en/latest/getting-started.html

That is not a valid page, should be without the .html? (https://docs.accurics.com/projects/accurics-terrascan/en/latest/getting-started/) 

### What I Did
followed link on readme

**Comment by cesar-rodriguez** [comment]
Thanks for the heads up @ah-f3. This was fixed via #945 which points to the new docs site.
